// Dev-only scenario driver: test.html?...#scenario
const errors = [];
addEventListener('error', (e) => errors.push(e.message));
const g = window.game, sc = location.hash.slice(1);
const wait = (ms) => new Promise((r) => setTimeout(r, ms));
const fire = (x, y) => { g.input.aimX = innerWidth * x; g.input.aimY = innerHeight * y; g.input.firePressed = true; };
async function run() {
  if (!g) { document.title = 'NO GAME ' + errors.join('|'); return; }
  await wait(600);
  if (sc === 'income') { const T = Number(new URLSearchParams(location.search).get('run') ?? 60000); const t0 = g.time, e0 = g.earned; const end = performance.now() + T; while (performance.now() < end) { g.growCool = 1e9; await wait(400); } const dt = g.time - t0; window.__extra = { stage: g.progress.stage, secs: +dt.toFixed(1), earned: Math.round(g.earned - e0), rate: Math.round((g.earned - e0) / dt), fell: g.world.structures.filter((s) => s.fell).length, world: +(100 - 100 * g.world.remaining / g.world.total).toFixed(2) }; }
  if (sc === 'hydrant') { const { T } = await import('./src/materials.js'); const w = g.world, m = g.monster; let found = null, best = 1e9; for (let z = 0; z < w.sz; z++) for (let x = 0; x < w.sx; x++) { for (let y = 1; y < 80; y++) if (w.get(x, y, z) === T.HYDRANT) { const d = Math.hypot(x - m.x, z - m.z); if (d < best) { best = d; found = [x, y, z]; } break; } } let n = 0; if (found) { m.x = found[0] - 14; m.z = found[2]; m.heading = 0; g.camYaw = Math.PI / 2; await wait(800); g.fire.spot(found[0] + 5, found[1], found[2] + 3, 3, 20, true); await wait(700); g.destruction.sphere(found[0], found[1] + 1, found[2], 2, 30, {}); await wait(2500); n = g.reactions.jets.length; } window.__extra = { found, jets: n, spots: g.fire.spots.filter((s) => s.flames).length }; }
  if (sc === 'units') { const T = Number(new URLSearchParams(location.search).get('run') ?? 40000); const end = performance.now() + T; let maxU = 0, maxH = 0, jets = 0, shots = 0; while (performance.now() < end) { await wait(300); maxU = Math.max(maxU, g.actors.units.length); maxH = Math.max(maxH, g.actors.helis.length); jets = Math.max(jets, g.actors.jets.length); shots = Math.max(shots, g.actors.shots.length); } const st = g.progress.stats; window.__extra = { wanted: g.wanted, units: g.actors.units.map((u) => u.kind + ':' + u.state).join(','), helis: g.actors.helis.map((h) => h.kind).join(','), maxU, maxH, jets, shots, burning: g.fire.n, ach: g.progress.achieved.length, stats: Object.fromEntries(Object.entries(st).filter(([, v]) => v).map(([k, v]) => [k, Math.round(v)])) }; }
  if (sc === 'jetgear') { const which = Number(new URLSearchParams(location.search).get('n') ?? 0); const list = g.unlockedTools(); g.selectTool(list[which]); g.input.aimX = innerWidth * 0.8; g.input.aimY = innerHeight * 0.75; await wait(1200); g.input.firePressed = true; await wait(250); window.__extra = { tool: g.tool, look: +g.monster.pose.look.toFixed(2), pitch: +g.monster.pose.aimPitch.toFixed(2), heading: +g.monster.heading.toFixed(2), yaw: +g.camYaw.toFixed(2) }; }
  if (sc === 'trophies') { g.stat('vox', 5000); g.stat('jumps', 20); await wait(1500); const n = document.querySelectorAll('.toast').length; if (new URLSearchParams(location.search).get('open')) g.hud.openAchievements(); window.__extra = { toasts: n, ach: g.progress.achieved.length }; }
  if (sc === 'burn') { const { T } = await import('./src/materials.js'); const w = g.world, m = g.monster; let best = 1e9, f = null; for (let z = 0; z < w.sz; z += 2) for (let x = 0; x < w.sx; x += 2) for (let y = 12; y < 40; y++) { const t = w.get(x, y, z); if (t === T.LEAF || t === T.LEAF_LIGHT || t === T.LEAF_DARK) { const d = Math.hypot(x - m.x, z - m.z); if (d > 20 && d < best) { best = d; f = [x, y, z]; } break; } } if (f) { m.x = f[0] - 22; m.z = f[2]; g.camYaw = Math.PI / 2; await wait(500); g.fire.heatSphere(f[0], f[1], f[2], 4, 3, 40); const log = []; for (let i = 0; i < 10; i++) { await wait(1000); log.push(g.fire.n); } window.__extra = { f, log, lit: g.progress.stats.fires, units: g.actors.units.map((u) => u.kind + ':' + u.state).join(','), wanted: g.wanted }; } }
  if (sc === 'leapfar') { const m = g.monster, out = {}; const run = async (name, dbl, sprint) => { await wait(1200); g.input.keys.add('KeyW'); if (sprint) g.input.keys.add('ShiftLeft'); await wait(300); const x0 = m.x, z0 = m.z; let top = 0; const y0 = m.y; g.input.jumpBtn = true; g.doAction('stomp'); if (dbl) { await wait(380); g.doAction('stomp'); } for (let i = 0; i < 80; i++) { await wait(40); top = Math.max(top, m.y - y0); if (m.onGround) break; } out[name] = [Math.round(Math.hypot(m.x - x0, m.z - z0)), Math.round(top)]; g.input.jumpBtn = false; g.input.keys.delete('KeyW'); g.input.keys.delete('ShiftLeft'); }; await run('single', false, false); await run('double', true, false); await run('sprintDouble', true, true); window.__extra = { h: +m.h.toFixed(1), out }; }
  if (sc === 'alarm') { const log = []; const t0 = g.time; let first = null; for (let i = 0; i < 110; i++) { await wait(500); if (first === null && g.actors.units.length) first = +(g.time - t0).toFixed(1); if (i === 50) g.setIdle(false); if (i % 10 === 9) log.push(+g.alarm.toFixed(2) + '/' + g.actors.units.map((u) => u.state[0]).join('')); } window.__extra = { first, log, h: +g.monster.h.toFixed(1), unit: g.world.unit }; }
  if (sc === 'traffic') { const T = Number(new URLSearchParams(location.search).get('run') ?? 20000); const t0 = g.traffic.cars.map((c) => [c.x, c.z]); const n0 = t0.length; let waits = 0, samples = 0; const end = performance.now() + T; while (performance.now() < end) { await wait(500); for (const c of g.traffic.cars) { samples++; if (c.wait > 0) waits++; } } const w = g.world; let offroad = 0; for (const c of g.traffic.cars) { const top = w.get(Math.floor(c.x), Math.floor(c.y) - 1, Math.floor(c.z)); if (![5, 6].includes(top) && top !== 0) offroad++; } window.__extra = { n0, n: g.traffic.cars.length, want: g.traffic.want, waiting: +(waits / Math.max(1, samples)).toFixed(2), offroad, units: g.actors.units.map((u) => u.kind + ':' + u.state + (u.road ? ':road' : '')).join(','), wrecked: g.progress.stats.cars, alarm: +g.alarm.toFixed(2) }; }
  if (sc === 'cling') { const m = g.monster, w = g.world; let best = null, bd = 1e9; for (const st of g.hud.major) { if (st.top - st.y0 < 60 || st.x1 - st.x0 < 30) continue; const d = Math.hypot((st.x0 + st.x1) / 2 - m.x, (st.z0 + st.z1) / 2 - m.z); if (d < bd) { bd = d; best = st; } } const log = []; if (best) { m.x = (best.x0 + best.x1) / 2; m.z = best.z0 - m.h * 1.5 - 4; m.y = w.heightBelow(m.x, m.z, 40); g.camYaw = 0; await wait(600); g.input.keys.add('KeyW'); g.input.jumpBtn = true; g.doAction('stomp'); await wait(250); g.input.jumpBtn = false; for (let i = 0; i < 25; i++) { await wait(80); if (m.cling) break; } log.push(['grab', !!m.cling, Math.round(m.y)]); g.input.keys.delete('KeyW'); await wait(700); log.push(['hold', !!m.cling, Math.round(m.y)]); g.input.keys.add('KeyW'); await wait(1200); g.input.keys.delete('KeyW'); log.push(['up', !!m.cling, Math.round(m.y)]); g.input.keys.add('KeyS'); await wait(500); g.input.keys.delete('KeyS'); log.push(['down', !!m.cling, Math.round(m.y)]); const x1 = m.x, z1 = m.z; g.input.keys.add('KeyD'); await wait(3500); g.input.keys.delete('KeyD'); log.push(['side', !!m.cling, Math.round(m.x - x1), Math.round(m.z - z1), m.cling && [m.cling.dx, m.cling.dz].map(Math.round).join()]); g.doAction('stomp'); await wait(150); const back = Math.round(Math.hypot(m.x - x1, m.z - z1)); g.input.keys.add('KeyW'); await wait(900); log.push(['jump', !!m.cling, Math.round(m.y)]); await wait(6000); g.input.keys.delete('KeyW'); log.push(['top', !!m.cling, m.onGround, Math.round(m.y), best.top]); void back; } window.__extra = { h: +m.h.toFixed(1), log }; }
  if (sc === 'frail') { const m = g.monster, w = g.world; const kinds = (new URLSearchParams(location.search).get('kind') ?? 'wheel').split(','); const st = w.structures.find((s) => kinds.includes(s.kind) && s.total > 100); const out = {}; if (st) { const cx = (st.x0 + st.x1) >> 1, cz = (st.z0 + st.z1) >> 1; m.x = cx; m.z = st.z1 + 30; g.camYaw = Math.PI; await wait(500); const r0 = st.remaining; let n = 0; for (let x = st.x0; x <= cx - 2; x += 3) for (let z = st.z0; z <= st.z1; z += 3) { const y = st.y0 + 2; if (w.get(x, y, z) && w.footprint[x + w.sx * z] === st.id) { g.destruction.sphere(x, y, z, 3, 40, { quiet: true }); n++; } } out.cuts = n; await wait(5000); out.kind = st.kind; out.before = r0; out.after = st.remaining; out.left = +(st.remaining / st.total).toFixed(2); out.fell = g.frail.fell; out.bodies = g.bodies.list.length; } const sims = []; let hang = 0; window.__extra = { ...out, sims, hang }; }
  if (sc === 'swim') { const m = g.monster; g.input.keys.add('KeyW'); await wait(500); const y0 = m.y; g.doAction('stomp'); let top = 0, strokes = 0; for (let i = 0; i < 40; i++) { await wait(100); top = Math.max(top, m.y - y0); if (i % 6 === 5) { g.doAction('stomp'); strokes++; } } g.input.keys.delete('KeyW'); const t0 = performance.now(); while (!m.onGround && performance.now() - t0 < 6000) await wait(100); window.__extra = { h: +m.h.toFixed(1), top: Math.round(top), strokes, sinkSecs: +((performance.now() - t0) / 1000).toFixed(1), swimmers: g.traffic.swimmers.map((s) => s.kind[0]).join(''), burning: g.fire.n, grav: g.world.grav }; }
  if (sc === 'see') { const q = new URLSearchParams(location.search), kinds = (q.get('kind') ?? '').split(','), back = Number(q.get('back') ?? 60); const st = g.world.structures.find((s) => kinds.includes(s.kind) && s.total > 100); if (st) { const m = g.monster; m.x = (st.x0 + st.x1) / 2; m.z = st.z1 + back; m.y = g.world.heightBelow(m.x, m.z, 60); m.heading = Math.PI; g.camYaw = Math.PI; g.pitchOffset = Number(q.get('pitch') ?? 0); await wait(2500); } window.__extra = { found: st ? [st.kind, st.x1 - st.x0, st.top - st.y0, st.z1 - st.z0, st.total] : null, water: g.world.water ? g.world.water.rects.length : 0, boats: g.traffic.swimmers.length, eggs: g.world.structures.length }; }
  if (sc === 'jetcrash') { const m = g.monster; let bounces = 0, was = false, minY = 1e9, inside = 0, n = 0; g.input.keys.add('KeyS'); await wait(1500); g.input.keys.delete('KeyS'); const end = performance.now() + 14000; while (performance.now() < end) { await wait(50); n++; if (m.bounce > 0 && !was) bounces++; was = m.bounce > 0; minY = Math.min(minY, m.y); if (g.world.get(Math.floor(m.x), Math.floor(m.y), Math.floor(m.z))) inside++; } window.__extra = { bounces, minY: Math.round(minY), ground: g.world.spawn[1], insideShare: +(inside / n).toFixed(2), world: +(100 - 100 * g.world.remaining / g.world.total).toFixed(2) }; }
  if (sc === 'punch') { g.input.keys.add('KeyW'); await wait(1500); g.input.keys.delete('KeyW'); for (let i = 0; i < 12; i++) { fire(0.5, 0.45); await wait(350); } }
  if (sc === 'walk') { g.input.keys.add('KeyW'); await wait(4000); }
  if (sc === 'shoot') { for (let i = 0; i < 10; i++) { fire(0.35 + i * 0.03, 0.42); await wait(450); } }
  if (sc === 'hold') { g.input.aimX = innerWidth * 0.5; g.input.aimY = innerHeight * 0.4; g.input.fire = true; await wait(3000); }
  if (sc === 'rampage') { g.input.keys.add('KeyW'); for (let i = 0; i < 16; i++) { fire(0.3 + (i % 5) * 0.1, 0.35 + (i % 3) * 0.08); await wait(400); if (i % 4 === 3) g.doAction('stomp'); } g.input.keys.delete('KeyW'); window.__extra = 'maxms'; }
  if (sc === 'flyshoot') { g.doAction('camera'); await wait(300); for (let i = 0; i < 8; i++) { fire(0.4 + i * 0.03, 0.55); await wait(450); } }
  if (sc === 'tools') { g.input.keys.add('KeyW'); await wait(1200); g.input.keys.delete('KeyW'); for (const t of ['fist', 'throw', 'throw', 'cannon', 'dynamite', 'rocket', 'sword', 'sword', 'beam']) { g.selectTool(t); await wait(100); fire(0.5, 0.42); g.input.fire = t === 'beam'; await wait(700); } g.input.fire = false; g.doAction('roar'); await wait(500); g.doAction('stomp'); await wait(2500); }
  if (sc === 'grow') { for (let i = 0; i < 3; i++) { g.gain += 1e7; await wait(2300); } }
  if (sc === 'worlds') { g.hud.openWorlds(); }
  if (sc === 'parent') { g.hud.openParent(); }
  if (sc === 'win') { for (const s of g.hud.major) { s.done = true; } g.structureDone(g.hud.major[0]); await wait(1500); }
  if (sc === 'touch') { g.input.device = 'touch'; g.hud.requestHint('fist', true); g.input.stick.on = true; g.input.stick.y = -1; g.input.stick.x = 0.3; await wait(1500); for (let i = 0; i < 5; i++) { fire(0.55, 0.4); await wait(350); } }
  if (sc === 'lap') { g.input.keys.add('KeyW'); await wait(9000); g.input.keys.delete('KeyW'); window.__extra = { meshes: g.chunkMeshes.size, dirty: g.world.dirty.size, mem: (g.world.memoryBytes() / 1e6) | 0 }; }
  if (sc === 'jump') { g.doAction('stomp'); await wait(450); }
  if (sc === 'boom') { g.input.keys.add('KeyW'); await wait(1200); g.input.keys.delete('KeyW'); fire(0.5, 0.4); await wait(250); g.doAction('stomp'); await wait(1750); fire(0.5, 0.42); await wait(250); }
  if (sc === 'whip') { g.input.keys.add('KeyW'); await wait(Number(new URLSearchParams(location.search).get('walk') ?? 1500)); g.input.keys.delete('KeyW'); for (let i = 0; i < 3; i++) { fire(0.5, 0.45); await wait(700); } fire(0.5, 0.45); await wait(330); }
  if (sc === 'burn') { for (let i = 0; i < 4; i++) { fire(0.3 + i * 0.13, 0.5); await wait(700); } await wait(2500); }
  if (sc === 'hop') { g.input.keys.add('KeyW'); g.input.jumpBtn = true; g.doAction('stomp'); await wait(520); }
  if (sc === 'avenue') { g.monster.place(776, 12, 660, 0); g.camYaw = 0; await wait(2500); }
  if (sc === 'street') { g.monster.place(708, 12, 716, 1.2); g.camYaw = 1.2; g.pitchOffset = -0.1; await wait(2500); }
  if (sc === 'above') { g.fly = true; g.flyPos = [516, 150, 380]; g.camYaw = 0; g.flyPitch = -0.45; await wait(3500); }
  const moves = () => [...document.querySelectorAll('#toolbar .btn')].length;
  if (sc === 'allmoves') { g.input.keys.add('KeyW'); await wait(900); g.input.keys.delete('KeyW'); const list = g.unlockedTools(); for (const id of list) { g.selectTool(id); g.input.aimX = innerWidth * 0.5; g.input.aimY = innerHeight * 0.42; await wait(100); g.input.firePressed = true; await wait(1300); g.input.heavyPressed = true; await wait(3600); } window.__extra = { moves: list, buttons: moves(), helis: g.actors.helis.length, heat: +g.heat.toFixed(2) }; }
  if (sc === 'heavy') { g.input.keys.add('KeyW'); await wait(Number(new URLSearchParams(location.search).get('walk') ?? 900)); g.input.keys.delete('KeyW'); g.input.aimX = innerWidth * 0.5; g.input.aimY = innerHeight * 0.42; g.input.heavyPressed = true; await wait(Number(new URLSearchParams(location.search).get('at') ?? 700)); }
  if (sc === 'shove') { g.camYaw = 0.5; g.input.keys.add('KeyW'); g.input.keys.add('ShiftLeft'); await wait(Number(new URLSearchParams(location.search).get('run') ?? 5000)); g.input.keys.delete('KeyW'); await wait(1500); window.__extra = { fell: g.world.structures.filter((s) => s.fell).length, done: g.world.structures.filter((s) => s.major && s.done).length, helis: g.actors.helis.length, heat: +g.heat.toFixed(2), failing: g.stability.failing.length }; }
  if (sc === 'diag') { g.input.keys.add('KeyW'); g.input.keys.add('ShiftLeft'); await wait(2500); const m = g.monster, w = g.world, h = m.h, r = h * 0.22, stepH = Math.max(1.5, h * 0.3), out = [];
    for (let s = -1; s <= 1; s++) for (let k = 0; k < 5; k++) { const x = m.x + 0 - 1 * r * s * 0.8, z = m.z + r + 1.5, y = Math.floor(m.y + stepH + 1 + (h * 0.75 - stepH) * (k / 4)); const t = w.get(Math.floor(x), y, Math.floor(z)); if (t) out.push([Math.floor(x), y, Math.floor(z), t, w.structures[w.footprint[Math.floor(x) + w.sx * Math.floor(z)]].kind].join(':')); }
    window.__extra = { pos: [m.x | 0, m.y | 0, m.z | 0, m.heading.toFixed(2)], out }; }
  if (sc === 'jet') { const list = g.unlockedTools(); g.input.keys.add('KeyD'); await wait(700); g.input.keys.delete('KeyD'); for (const id of list) { g.selectTool(id); g.input.aimX = innerWidth * 0.5; g.input.aimY = innerHeight * 0.6; await wait(100); g.input.firePressed = true; await wait(900); g.input.heavyPressed = true; await wait(2300); } window.__extra = { moves: list, helis: g.actors.helis.length, y: g.monster.y | 0, sweep: (g.sweeper.head - g.sweeper.tail + 32768) % 32768 }; }
  if (sc === 'dj') { const m = g.monster, log = []; const snap = (l) => log.push(l + ':y' + (m.y - 4).toFixed(0) + ',j' + m.jumps + ',flip' + m.pose.flip.toFixed(2) + ',g' + (m.onGround ? 1 : 0));
    g.input.jumpBtn = true; g.doAction('stomp'); await wait(380); snap('up1'); g.doAction('stomp'); await wait(60); snap('second'); g.doAction('stomp'); await wait(200); snap('mid'); const shotAt = [m.y | 0, m.pose.flip.toFixed(2)]; window.__extra = { log, shotAt }; }
  if (sc === 'dj2') { const m = g.monster, log = []; const snap = (l) => log.push(l + ':y' + (m.y - 4).toFixed(0) + ',j' + m.jumps + ',flip' + m.pose.flip.toFixed(2) + ',g' + (m.onGround ? 1 : 0));
    g.input.jumpBtn = true; g.doAction('stomp'); await wait(380); g.doAction('stomp'); let top = 0; for (let i = 0; i < 40; i++) { await wait(60); top = Math.max(top, m.y - 4); if (m.onGround) break; } snap('landed'); g.doAction('stomp'); await wait(100); snap('again'); window.__extra = { log, top: top | 0, h: m.h, world: +(100 - 100 * g.world.remaining / g.world.total).toFixed(2) }; }
  if (sc === 'idlestop') { await wait(3000); const a = g.idle; window.dispatchEvent(new KeyboardEvent('keydown', { code: 'KeyW' })); await wait(200); const b = g.idle; window.dispatchEvent(new KeyboardEvent('keyup', { code: 'KeyW' })); window.dispatchEvent(new KeyboardEvent('keydown', { code: 'KeyI' })); await wait(200); const c = g.idle; window.dispatchEvent(new KeyboardEvent('keydown', { code: 'KeyI' })); await wait(400); const d = g.idle; g.hud.btnIdle.click(); await wait(200); window.__extra = { startOn: a, afterW: b, afterI: c, afterI2: d, afterButton: g.idle, btnSel: g.hud.btnIdle.classList.contains('sel') }; }
  if (sc === 'pound' || sc === 'late') { const m = g.monster, log = []; const q = new URLSearchParams(location.search); if (q.has('px')) { m.place(Number(q.get('px')), 12, Number(q.get('pz')), 0); g.camYaw = 0; } g.input.keys.add('KeyW'); await wait(Number(q.get('walk') ?? 1600)); const p0 = g.progress.power;
    g.input.jumpBtn = true; g.doAction('stomp'); await wait(380); g.doAction('stomp'); let ready = -1;
    for (let i = 0; i < 200; i++) { await wait(16); if (m.poundReady()) { ready = i; break; } }
    if (sc === 'late') { for (let i = 0; i < 300 && m.poundReady(); i++) await wait(16); }
    const yTop = m.y; g.doAction('stomp'); await wait(40); const started = !!m.pound, x0 = m.x, z0 = m.z; let fallShot = null, maxChain = 0, frames = 0;
    for (let i = 0; i < 300 && !m.onGround; i++) { await wait(16); frames++; if (m.pound) { maxChain = Math.max(maxChain, m.pound.chain); if (m.pound.falling && !fallShot) fallShot = { sq: m.pose.squash, leg: +m.pose.j.legL[0].toFixed(2) }; } }
    const drift = Math.hypot(m.x - x0, m.z - z0); await wait(150); const stunned = m.stun > 0, xs = m.x, zs = m.z; await wait(120); const movedInStun = Math.hypot(m.x - xs, m.z - zs);
    await wait(900); window.__extra = { ready, started, yTop: yTop | 0, yEnd: m.y | 0, drift: +drift.toFixed(2), maxChain, fallShot, stunned, movedInStun: +movedInStun.toFixed(2), gained: (g.progress.power - p0) | 0, stage: g.progress.stage }; }
  if (sc === 'idlewalk') { const m = g.monster, size = g.cam.wrap; let path = 0, lx = m.x, lz = m.z; const wd = (d) => { if (!size) return d; d %= size; return d > size / 2 ? d - size : d < -size / 2 ? d + size : d; }; const x0 = m.x, z0 = m.z; let far = 0;
    for (let i = 0; i < 180; i++) { await wait(200); path += Math.hypot(wd(m.x - lx), wd(m.z - lz)); lx = m.x; lz = m.z; far = Math.max(far, Math.hypot(wd(m.x - x0), wd(m.z - z0))); }
    window.__extra = { path: path | 0, farthest: far | 0, h: +m.h.toFixed(0), done: g.hud.major.filter((s) => s.done).length, stage: g.progress.stage }; }
  if (sc === 'beam') { g.monster.place(516, 12, 600, 0); g.camYaw = 0.5; await wait(300); g.input.aimX = innerWidth * 0.22; g.input.aimY = innerHeight * 0.3; await wait(100); g.input.heavyPressed = true; let n = 0; for (let i = 0; i < 300; i++) { await wait(16); const r = g.tools.rays.find((x) => x.life < 0.05 && Math.hypot(x.bx - x.ax, x.bz - x.az) > 60); if (r && ++n > 25) { g.paused = true; window.__extra = { len: Math.hypot(r.bx - r.ax, r.bz - r.az) | 0 }; break; } } }
  if (sc.startsWith('mobile')) { g.input.device = 'touch'; g.hud.refreshTools(); await wait(300);
    const check = () => { const bad = [], seen = []; for (const b of document.querySelectorAll('#hud .btn, #hud a')) { const r = b.getBoundingClientRect(); if (!r.width || getComputedStyle(b).visibility === 'hidden') continue; const cx = r.left + r.width / 2, cy = r.top + r.height / 2, top = document.elementFromPoint(cx, cy); const name = (b.id || b.dataset.id || b.textContent).slice(0, 12); seen.push(name + ':' + Math.round(r.width)); if (!top || !(top === b || b.contains(top))) bad.push(name + ' covered by ' + (top ? (top.id || top.className || top.tagName) : 'nothing')); if (r.left < 0 || r.top < 0 || r.right > innerWidth || r.bottom > innerHeight) bad.push(name + ' off screen'); if (Math.min(r.width, r.height) < 40 && b.tagName === 'BUTTON') bad.push(name + ' too small ' + Math.round(r.width)); } return { seen, bad }; };
    const closed = check(); g.hud.toggleMenu(true); await wait(100); const open = check(); const out = { size: innerWidth + 'x' + innerHeight, body: document.body.className, closed, openBad: open.bad, openSeen: open.seen.length };
    if (sc === 'mobile') g.hud.toggleMenu(false);
    if (sc === 'mobilemenu') { await wait(100); }
    if (sc === 'mobileworlds') { g.hud.toggleMenu(false); g.hud.openWorlds(); await wait(200); const sh = document.querySelector('.sheet'); out.sheet = { h: sh.clientHeight, scroll: sh.scrollHeight, touchAction: getComputedStyle(sh).touchAction, canvasTA: getComputedStyle(g.canvas).touchAction, bodyTA: getComputedStyle(document.body).touchAction }; }
    if (sc === 'mobileplay') { g.hud.toggleMenu(false); const p0 = g.progress.power; g.input.stick.on = true; g.input.stick.y = -1; await wait(1500); g.input.stick.on = false; g.input.stick.y = 0; const ev = (el) => el.dispatchEvent(new PointerEvent('pointerdown', { bubbles: true })); for (let i = 0; i < 4; i++) { ev(g.hud.btnLight); await wait(600); } const t0 = g.tool; ev(g.hud.btnCycle); await wait(100); const t1 = g.tool; ev(g.hud.btnHeavy); await wait(1800); ev(document.querySelector('#abilities [data-id=stomp]')); await wait(300); const jumped = !g.monster.onGround; out.play = { gained: (g.progress.power - p0) | 0, cycled: t0 + '>' + t1, jumped, lightIcon: g.hud.btnLight.textContent }; }
    window.__extra = out; }
  if (sc === 'desk') { await wait(300); const vis = (id) => { const e = document.getElementById(id); return !!e && getComputedStyle(e).display !== 'none' && e.getBoundingClientRect().width > 0; }; window.__extra = { body: document.body.className, menuBtn: vis('menuBtn'), touchpad: vis('touchpad'), toolbar: vis('toolbar'), topright: vis('topright'), legal: vis('legal'), legal2: vis('legal2'), icons: getComputedStyle(document.querySelector('#worldbar .icons')).display }; }
  if (sc === 'iostouch') { const m = g.monster, c = g.canvas, x0 = m.x, z0 = m.z; const T = (type, id, x, y) => { const t = new Touch({ identifier: id, target: c, clientX: x, clientY: y }); c.dispatchEvent(new TouchEvent(type, { changedTouches: [t], touches: type === 'touchend' ? [] : [t], bubbles: true, cancelable: true })); };
    const id = Number(new URLSearchParams(location.search).get('tid') ?? -1463293746); T('touchstart', id, 80, innerHeight - 80); await wait(50); T('touchmove', id, 80, innerHeight - 160); await wait(1500); const moved = Math.hypot(m.x - x0, m.z - z0), knob = g.input.stick.y; T('touchend', id, 80, innerHeight - 160); await wait(300); const x1 = m.x, z1 = m.z; await wait(400);
    const p0 = g.progress.power; T('touchstart', id - 7, innerWidth * 0.55, innerHeight * 0.4); await wait(80); T('touchend', id - 7, innerWidth * 0.55, innerHeight * 0.4); await wait(900);
    window.__extra = { id, device: g.input.device, moved: +moved.toFixed(1), knobY: knob, stoppedAfter: +Math.hypot(m.x - x1, m.z - z1).toFixed(2), tapAttacked: g.progress.power > p0 || !!g.tools.act || g.tools.cool > -0.9 }; }
  if (sc === 'settings') { g.hud.btnGear.click(); await wait(200); const sh = document.querySelector('.sheet'); const labels = [...sh.querySelectorAll('h2, label, button, p')].map((e) => e.childNodes[0].textContent.slice(0, 34)); [...sh.querySelectorAll('button')].find((b) => b.textContent.startsWith('Von vorn')).click(); await wait(100); const confirmVisible = [...sh.querySelectorAll('button')].filter((b) => b.offsetParent).map((b) => b.textContent); window.__extra = { top: [...document.querySelectorAll('#topright .btn')].filter((b) => b.offsetParent).map((b) => b.textContent), gearOpacity: getComputedStyle(g.hud.btnGear).opacity, labels, confirmVisible }; }
  if (sc === 'stomp') { for (let i = 0; i < 3; i++) { g.doAction('stomp'); await wait(1200); } }
  await wait(400);
  const p = g.progress;
  const info = document.createElement('pre');
  info.style.cssText = 'position:fixed;left:8px;bottom:90px;margin:0;font:12px monospace;background:#000a;color:#fff;padding:4px;z-index:9';
  info.textContent = `err:${errors.join('|') || '-'} ms:${g.frameMs.toFixed(1)} stage:${p.stage} power:${p.power | 0} bodies:${g.bodies.list.length} debris:${g.debris.n} chunks:${g.chunkMeshes.size} dirty:${g.world.dirty.size} world:${(100 - 100 * g.world.remaining / g.world.total).toFixed(1)}%`;
  document.body.appendChild(info);
}
run();
